batches_per_step: 20
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
description: pedestrian_detection_single
entrypoint: model_def:ObjectDetectionModel
hyperparameters:
  global_batch_size: 4
  learning_rate: 0.00125
  momentum: 0.75
  weight_decay: 0.0005
min_validation_period: 1
searcher:
  max_steps: 4
  metric: val_avg_iou
  name: single
  smaller_is_better: false
