batches_per_step: 20
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
description: distributed_training
entrypoint: model_def:ObjectDetectionModel
hyperparameters:
  global_batch_size: 16
  learning_rate: 0.01
  momentum: 0.8
  weight_decay: 0.0005
min_validation_period: 1
resources:
  slots_per_trial: 4
searcher:
  max_steps: 20
  metric: val_avg_iou
  name: single
  smaller_is_better: false
